"""Add nullable=False to Board title/content

Revision ID: 2d9060d1b5fe
Revises: 8a081195885f
Create Date: 2026-02-03 13:09:32.122738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d9060d1b5fe'
down_revision: Union[str, Sequence[str], None] = '8a081195885f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boards', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('boards', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('boards', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('boards', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
